### ISSUE TITLE
Trireme is being invoked

### ISSUE THREAD

**Issue by francisdb** [sbt/sbt-js-engine#56]
Tried to deploy my freshly updated play 2.6 app on Heroku and got this:

```
[info] LESS compiling on 1 source(s)
[error] java.lang.NoSuchMethodError: org.mozilla.javascript.ScriptRuntime.setObjectProp(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;Lorg/mozilla/javascript/Context;Lorg/mozilla/javascript/Scriptable;)Ljava/lang/Object;
[error] 	at io.apigee.trireme.node10.main.trireme._c_anonymous_1(trireme.js:37)
[error] 	at io.apigee.trireme.node10.main.trireme.call(trireme.js)
[error] 	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
[error] 	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3102)
[error] 	at io.apigee.trireme.node10.main.trireme.call(trireme.js)
[error] 	at io.apigee.trireme.core.internal.ScriptRunner.runScript(ScriptRunner.java:762)
[error] 	at io.apigee.trireme.core.internal.ScriptRunner$4.run(ScriptRunner.java:702)
[error] 	at org.mozilla.javascript.Context.call(Context.java:488)
[error] 	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:504)
[error] 	at io.apigee.trireme.core.internal.ScriptRunner.call(ScriptRunner.java:697)
[error] 	at io.apigee.trireme.core.ScriptFuture.run(ScriptFuture.java:183)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[error] 	at java.lang.Thread.run(Thread.java:748)
```

with `export SBT_OPTS="$SBT_OPTS -Dsbt.jse.engineType=Trireme"` I can reproduce this locally

Is this the correct repo to post this issue?

If found some hints on a rhino version mismatch here
https://github.com/ksoichiro/gradle-web-resource-plugin/blob/master/build.gradle#L51
http://ant.1045680.n5.nabble.com/java-lang-NoSuchMethodError-org-mozilla-javascript-Context-getDebuggableEngine-Lorg-mozilla-javascri-td1343973.html

**Comment by francisdb** [comment]
Using strict conflict management for the project build I found this:
```
com.typesafe.sbt#sbt-js-engine;1.1.2 (needed by [com.typesafe.sbt#sbt-less;1.1.1]) conflicts with com.typesafe.sbt#sbt-js-engine;1.2.1 (needed by [com.typesafe.play#sbt-plugin;2.6.1])
```

Then I tried a forced downgrade of sbt-js-engine which fixes the issue

plugins.sbt
```
...
//conflictManager := ConflictManager.strict
libraryDependencies ++= Seq(
  "com.typesafe.sbt" % "sbt-js-engine" % "1.1.2" force()
)
```

I guess `sbt-less` (and other plugins) needs a new release?

**Comment by wsargent** [comment]
I'm also running into this on https://github.com/playframework/play-scala-websocket-example when there is no node install and the system relies on Rhino.

**Comment by estsauver** [comment]
I'm seeing this as well.

**Comment by llb4ll** [comment]
Can confirm the issue - I also submitted an issue to the sbt-less project regarding this: https://github.com/sbt/sbt-less/issues/95

**Comment by llb4ll** [comment]
@estsauver 
I managed to force downgrade by adding this to `project/plugins.sbt`:
(Adding it to `build.sbt` results in the unresolved dependency error as you described.)
```
// there is a compatibility issue with sbt-less and the latest sbt-js-engine - downgrade version until fixed
dependencyOverrides += "com.typesafe.sbt" % "sbt-js-engine" % "1.1.4"
```

**Comment by francisdb** [comment]
@llb4ll is that the only thing you had to change in combination with `addSbtPlugin("com.typesafe.sbt" % "sbt-less" % "1.1.1"` ?

Still fails here when building on heroku/OpenJDK 1.8:

```
       [info] LESS compiling on 1 source(s)
       [error] TypeError: [object Object] is not a function, it is object. (/tmp/scala_buildpack_build_dir/project/target/node-modules/webjars/less/lib/less/index.js#4)    at /tmp/scala_buildpack_build_dir/project/target/node-modules/webjars/less/lib/less/index.js:4
       [error]     at /tmp/scala_buildpack_build_dir/project/target/node-modules/webjars/less/lib/less-node/index.js:1
       [error]     at module.js:456
       [error]     at module.js:474
       [error]     at module.js:356
       [error]     at module.js:312
       [error]     at module.js:364
       [error]     at require (module.js:380)
       [error]     at /tmp/scala_buildpack_build_dir/project/target/node-modules/webjars/less/index.js:1
       [error]     at module.js:456
       [error]     at module.js:474
       [error]     at module.js:356
       [error]     at module.js:312
       [error]     at module.js:364
       [error]     at require (module.js:380)
       [error]     at /tmp/scala_buildpack_build_dir/target/less/lessc.js:14
       [error]     at /tmp/scala_buildpack_build_dir/target/less/lessc.js:3
       [error]     at module.js:456
       [error]     at module.js:474
       [error]     at module.js:356
       [error]     at module.js:312
       [error]     at module.js:497
       [error]     at startup (trireme.js:142)
       [error]     at trireme.js:923
       [info] 
       com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: TypeError: [object Object] is not a function, it is object. (/tmp/scala_buildpack_build_dir/project/target/node-modules/webjars/less/lib/less/index.js#4)    at /tmp/scala_buildpack_build_dir/project/target/node-modules/webjars/less/lib/less/index.js:4
           at /tmp/scala_buildpack_build_dir/project/target/node-modules/webjars/less/lib/less-node/index.js:1
           at module.js:456
           at module.js:474
           at module.js:356
           at module.js:312
           at module.js:364
           at require (module.js:380)
           at /tmp/scala_buildpack_build_dir/project/target/node-modules/webjars/less/index.js:1
           at module.js:456
           at module.js:474
           at module.js:356
           at module.js:312
           at module.js:364
           at require (module.js:380)
           at /tmp/scala_buildpack_build_dir/target/less/lessc.js:14
           at /tmp/scala_buildpack_build_dir/target/less/lessc.js:3
           at module.js:456
           at module.js:474
           at module.js:356
           at module.js:312
           at module.js:497
           at startup (trireme.js:142)
           at trireme.js:923
       
       	at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:215)
       	at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeJsOnEngine$1.apply(SbtJsTask.scala:187)
       	at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
       	at scala.util.Try$.apply(Try.scala:161)
       	at scala.util.Success.map(Try.scala:206)
       	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
       	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
       	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
       	at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
       	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
       	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
       	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
       	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
       [error] (web-assets:less) com.typesafe.sbt.jse.SbtJsTask$JsTaskFailure: TypeError: [object Object] is not a function, it is object. (/tmp/scala_buildpack_build_dir/project/target/node-modules/webjars/less/lib/less/index.js#4)    at /tmp/scala_buildpack_build_dir/project/target/node-modules/webjars/less/lib/less/index.js:4
       [error]     at /tmp/scala_buildpack_build_dir/project/target/node-modules/webjars/less/lib/less-node/index.js:1
       [error]     at module.js:456
       [error]     at module.js:474
       [error]     at module.js:356
       [error]     at module.js:312
       [error]     at module.js:364
       [error]     at require (module.js:380)
       [error]     at /tmp/scala_buildpack_build_dir/project/target/node-modules/webjars/less/index.js:1
       [error]     at module.js:456
       [error]     at module.js:474
       [error]     at module.js:356
       [error]     at module.js:312
       [error]     at module.js:364
       [error]     at require (module.js:380)
       [error]     at /tmp/scala_buildpack_build_dir/target/less/lessc.js:14
       [error]     at /tmp/scala_buildpack_build_dir/target/less/lessc.js:3
       [error]     at module.js:456
       [error]     at module.js:474
       [error]     at module.js:356
       [error]     at module.js:312
       [error]     at module.js:497
       [error]     at startup (trireme.js:142)
       [error]     at trireme.js:923
       [error] Total time: 4 s, completed Aug 16, 2017 9:11:08 AM
 !     ERROR: Failed to run sbt!
```

**Comment by llb4ll** [comment]
@francisdb Yes but I used sbt-less version 1.0.6.

This is my complete plugins.sbt files. Maybe it helps deleting the target directory in the project directory.

Here is my complete plugins.sbt for reference:

```
// The Play plugin
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.6.2")

// advanced stylesheets
addSbtPlugin("com.typesafe.sbt" % "sbt-less" % "1.0.6")

// compression of assets
addSbtPlugin("com.typesafe.sbt" % "sbt-gzip" % "1.0.1")

// fingerprinting assets (versioning)
addSbtPlugin("com.typesafe.sbt" % "sbt-digest" % "1.1.1")

// web asset pipeline
addSbtPlugin("com.typesafe.sbt" % "sbt-web" % "1.4.1")

// there is a compatibility issue with sbt-less and the latest sbt-js-engine - downgrade version until fixed
// https://github.com/sbt/sbt-less/issues/95
dependencyOverrides += "com.typesafe.sbt" % "sbt-js-engine" % "1.1.4"
```

**Comment by benmccann** [comment]
Trireme is no longer supported. It should not be called. It looks like sbt-less in on an old version of sbt-js-engine. Everything should use sbt-js-engine 1.2.1

**Comment by francisdb** [comment]
@benmccann is the only option then installing node.js?

**Comment by francisdb** [comment]
@llb4ll thanks, that sbt-less 1.0.6 downgrade in combination with sbt-js-engine 1.1.4 seems to have done the trick 🙌

**Comment by francisdb** [comment]
@benmccann trireme stills seems to be the default if node is not installed
https://github.com/sbt/sbt-js-engine/blob/6d402c4d4791e31c5caea9ab3f76ec58454dc255/src/main/scala/com/typesafe/sbt/jse/SbtJsEngine.scala#L68

**Comment by benmccann** [comment]
The npm module checks for Node:

    https://github.com/typesafehub/npm/blob/master/src/main/scala/com/typesafe/npm/Npm.scala#L35

I was thinking that sbt-less invokes npm, but I'm not 100% sure about that. Can you test with my PR to sbt-less to see if it solves your problem?

**Comment by francisdb** [comment]
@benmccann it can not solve my problems as I have no node installed and prefer to not have to install one :-)

**Comment by benmccann** [comment]
I'm afraid there's no solution to that. Trireme is unmaintained and is incompatible with newer versions of node and npm, so we can't realistically continue to use it. If we continue using Trireme then we'll get an even higher volume of complaints about how people can't use the latest version of various node/npm packages

**Comment by francisdb** [comment]
I understand, might make some time to get this working later. For now I can continue with the workaround.

**Comment by benmccann** [comment]
Great. If you end up getting Trireme to work with newer versions of node/npm we can reconsider adding it back

**Comment by francisdb** [comment]
Hehe, I meant I was going to get my CI/CD/Heroku build set up with node.js :-)

**Comment by benmccann** [comment]
That's much easier! :-)

**Comment by benmccann** [comment]
There's a new sbt-less 1.1.2 release. Can you guys try with it?

**Comment by benmccann** [comment]
We're having trouble reproducing. If you have a project where this is occurring can you comment on https://github.com/sbt/sbt-less/issues/95? Thanks!

**Comment by mkurz** [comment]
6 years later the situation did not change. Trieme still not being maintained.
Seems like the problem was fixed anyway according to the comments.
However, please use a local installed node.
